@startuml
'https://plantuml.com/sequence-diagram

autonumber
Mainframe Drop AminoAcid
actor Player
Player -> "v:Virologist": collect()
"v:Virologist"->"a:AminoAcid"++:discard(Virologist)
"a:AminoAcid"->"v:Virologist":SetAminoAcid
activate "v:Virologist"
"v:Virologist"-->"a:AminoAcid"
deactivate "v:Virologist"
"a:AminoAcid"-->"v:Virologist"--
"v:Virologist"-->Player

@enduml